spring.application.name=mnp
spring.datasource.url=jdbc:mysql://localhost:3306/mnp_db?useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=springstudent
spring.datasource.password=springstudent